name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release

# Disabled documentation build for fork - only needed for official TRL repository
# jobs:
#    build:
#     uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
#     with:
#       commit_sha: ${{ github.sha }}
#       package: trl
#       version_tag_suffix: ""
#       custom_container: huggingface/transformers-doc-builder
#     secrets:
#       hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - name: Skip documentation build
        run: echo "Documentation build skipped for fork"
